name: CI/CD for Godot Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Godot for headless build
      - name: Install Godot
        uses: firebelley/setup-godot@v1
        with:
          godot-version: 4.1.1

      # Export the game for Android
      - name: Export Game
        run: |
          mkdir -p Build/
          godot --export "Android" Build/game.apk

      # Save the build as an artifact
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: Build/game.apk
